ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS tax_amount_deducted NUMERIC,
  ADD COLUMN IF NOT EXISTS vcc_number TEXT,
  ADD COLUMN IF NOT EXISTS expiry_date TEXT,
  ADD COLUMN IF NOT EXISTS cvc TEXT;
